name: Clone Vendor Directory

on:
  workflow_dispatch:  # 允许手动触发工作流

jobs:
  clone-vendor-directory:
    runs-on: ubuntu-latest
    
    steps:
      # 1. 检出当前仓库代码
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. 禁用 Git LFS 并克隆仓库
      - name: Clone realmeGT6 vendor directory (skip LFS)
        run: |
          git config --global http.sslVerify false  # 如果需要跳过 SSL 验证（可选）
          git clone --depth 1 --branch master https://github.com/realme-kernel-opensource/realmeGT6-AndroidU-vendor-source.git temp-repo
          cd temp-repo
          GIT_LFS_SKIP_SMUDGE=1 git checkout master
          cp -r temp-repo/vendor ./vendor
          rm -rf temp-repo

      # 3. 提交并推送更改
      - name: Commit and push changes
        run: |
          git config user.name "github-actions"
          git config user.email "github-actions@github.com"
          git add vendor
          git commit -m "Add realmeGT6 vendor directory" || echo "No changes to commit"
          git push
