name: Clone Vendor Directory

on:
  push:
    branches:
      - main

jobs:
  clone-vendor:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Clone the vendor directory
        run: |
          git clone --depth 1 --branch master https://github.com/realme-kernel-opensource/realmeGT6-AndroidU-vendor-source.git
          cp -r realmeGT6-AndroidU-vendor-source/vendor ./vendor
